### ISSUE TITLE
BUG: Breaks on ipython 5.0 / prompt_toolkit

### ISSUE THREAD

**Issue by maxim-lian** [jlubcke/pytest-pycharm#4]
Thanks again for this wonderful plugin!

I recently upgraded to ipython 5.0. This replaces `read_line` with `prompt_toolkit`. Unfortunately that seems to break this plugin?

This is the stack trace after executing a `print` command in the debugger:

``` python
>>> print('a')
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1334, in do_it
    result = pydevconsole.console_exec(self.thread_id, self.frame_id, self.expression, dbg)
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevconsole.py", line 461, in console_exec
    need_more =  exec_code(CodeFragment(expression), updated_globals, frame.f_locals, dbg)
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevconsole.py", line 378, in exec_code
    interpreterInterface = get_interpreter()
  File "/home/ubuntu/.pycharm_helpers/pydev/pydevconsole.py", line 360, in get_interpreter
    interpreterInterface = InterpreterInterface(None, None, threading.currentThread())
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydev_bundle/pydev_ipython_console.py", line 26, in __init__
    self.interpreter = get_pydev_frontend(host, client_port, show_banner=show_banner)
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydev_bundle/pydev_ipython_console_011.py", line 485, in get_pydev_frontend
    _PyDevFrontEndContainer._instance = _PyDevFrontEnd(show_banner=show_banner)
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydev_bundle/pydev_ipython_console_011.py", line 315, in __init__
    self.ipython = PyDevTerminalInteractiveShell.instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 360, in __init__
    self.init_prompt_toolkit_cli()
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 238, in init_prompt_toolkit_cli
    self.pt_cli = CommandLineInterface(self._pt_app, eventloop=self._eventloop)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 81, in __init__
    self.input = input or StdinInput(sys.stdin)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/input.py", line 67, in __init__
    assert self.stdin.isatty()
AssertionError: assert <bound method DebugConsoleStdIn.isatty of <_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8>>()
 +  where <bound method DebugConsoleStdIn.isatty of <_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8>> = <_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8>.isatty
 +    where <_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8> = <_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8>
 +      where <_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8> = StdinInput(stdin=<_pydev_bundle.pydev_console_utils.DebugConsoleStdIn instance at 0x7fba1112f1b8>).stdin

```

**Comment by jlubcke** [comment]
Is this still an issue?

**Comment by maxim-lian** [comment]
I'm not sure. I'm not using PyCharm any longer, unfortunately
